# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb8d2884f307ce3f42bf7b0d13f8713a58fdca889d23cc7322a10c9b12b652e94701df5e4adfbe7fc6b5044e31ec49eeaa8e4457bcec3425f1890a633ffee88

test:
  secret_key_base: 52429d3c684fd1be29d48243153e180d16e03b8bc5f9e48764282c70ed9dc2887f337b70692f8f954be6edd37f95f27faf56bcf417958dc7413d2f1e128bf91a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
